### ISSUE TITLE
Interpolation Issue - Beta 8 - dblgrave

### ISSUE THREAD

**Issue by kenmcd** [Familjen-Sthlm/Familjen-Grotesk#1]
Files: FamiljenGroteskItalic.glyphs and FamiljenGrotesk-MediumItalic.otf (and .ttf)
There appears to be an interpolation issue with the dblgrave.
Looks like there is a different element order in the two masters.
Also affects the static Medium Italic fonts.

![2022-01-04_15-58-36](https://user-images.githubusercontent.com/844920/148140281-b88e2c89-87ea-4566-ad47-0644c7efc994.gif)

**Comment by ktkm** [comment]
You’re right. The order of outlines for the component dblgrave was reversed in the Regular master. Unfortunately, this affects all the interpolated static fonts. I’ll correct this in the next push. Thanks!
