### ISSUE TITLE
Two marks used in two mark-to-base lookups

### ISSUE THREAD

**Issue by ErwinDenissen** [Familjen-Sthlm/Familjen-Grotesk#3]
Both dotaccentcomb and dotaccentcomb_macroncomb are used in the two defined mark-to-base lookups, so one overrides the other. The last one is wrong, hence the outcome is wrong.

![TwoTimes](https://user-images.githubusercontent.com/77341841/162214612-576a81fa-c0be-4c62-aeaf-9807354b9cc7.png)

**Comment by ktkm** [comment]
I think I have resolved the issue. dotaccentcomb_macroncomb no longer uses the dotaccentcomb as a component. I’ll include the update in the next push. Thank you!

**Comment by ktkm** [comment]
Fixed in version 2.001

**Comment by ErwinDenissen** [comment]
It still uses the overlay anchor for /O/dotaccentcomb. You can't have two working anchors at the same time.

**Comment by ktkm** [comment]
I have been using the dotaccentcomb as a substitution for periodcentered.loclCAT. However, I could save some time by adding an extra anchor, not knowing this could impact Latin transcription. So, I’ll make the update in version 2.002. Thanks again.

**Comment by ErwinDenissen** [comment]
From what I understand is you do have a contextual substitution there for:

  sub periodcentered by periodcentered.loclCAT;

But nothing with dotaccentcomb.
